{
 "title": "Linky Nitrouze pbranly v3",
 "time": { "from": "now-7d", "to": "now-24h" },
 "templating": {
  "list": [
   { "name": "pdl", "label": "Point de livraison", "query": "\ta changer" },
   { "name": "price_STD", "label": "€ / kWh Base", "query": "0.15" },
   { "name": "price_HC", "label": "€ / kWh (HC)", "query": "0.1312" },
   { "name": "price_HP", "label": "€ / kWh (HP)", "query": "0.1749" },
   { "name": "surface_maison", "label": "Surface de la maison", "query": "109" }
  ]
 },
 "panels": [
  {
   "title": "Consommation Heures Pleines",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"kW\") FROM \"enedisgateway_detail\" WHERE (\"measure_type\" = 'HP' AND \"pdl\" =~ /^$pdl$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 2000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "measure_type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Heures Pleines ($price_HP€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"kW\") *$price_HP FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Tarif en HC/HP",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Classe Energetique",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT \"kWh\"  / $surface_maison FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       { "params": [ " / $surface_maison" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"Wh\") FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "measure_type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "measure_type", "operator": "=", "value": "HC" },
      { "condition": "AND", "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Consommation Heures Creuses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 2000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "measure_type", "operator": "=", "value": "HC" },
      { "condition": "AND", "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Heures Creuses ($price_HC€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"kW\") *$price_HC FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Période Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"W\") FROM \"enedisgateway_detail\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Tarif Base ($price_STD€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_daily",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Gain Base vs HC/HP",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "alias": "STD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_daily",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Consommation (J-1) en (k)W / Intervalle 30m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"W\") FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time(30m) fill(none) tz('America/New York')",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Conso. Hebdo. (J-1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kWh/Jour",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/) AND $timeFilter GROUP BY time(1d) tz('Europe/Paris')",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  { "title": "2021", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 0, "y": 18 } },
  { "title": "2020", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 9, "y": 18 } },
  { "title": "2019", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 18 } },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2021') ",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2021') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "current_year",
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2021') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    },
    {
     "alias": "last_year",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2020') "
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2020') ",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2020') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "current_year",
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2020') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    },
    {
     "alias": "last_year",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2019') "
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2019')",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2019" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"price\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2019')",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2019" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle en Wh",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "sum_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"Wh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2021')  GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    },
    {
     "alias": "sum_year1",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"Wh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2020')  GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    },
    {
     "alias": "sum_year2",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"Wh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"year\" = '2019')  GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation Horaire en kW",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "SELECT sum(\"W\") FROM \"enedisgateway_detail\" WHERE (\"pdl\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time(30m) fill(none) tz('America/New York')",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Consommation journaliere en kWh",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kWh/Jour",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "SELECT sum(\"kWh\") FROM \"enedisgateway_daily\" WHERE (\"pdl\" =~ /^$pdl$/) AND $timeFilter GROUP BY time(1d) tz('Europe/Paris')",
     "select": [
      [
       { "params": [ "kWh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  }
 ]
}